import Head from 'next/head';
import styles from '../styles/Home.module.css';
import axios from '../src/config/api';
import { useEffect, useState } from 'react';
import {
  Box,
  Button,
  Flex,
  Text,
  Hide,
  Icon,
  Input,
  InputGroup,
  InputRightElement,
  Show,
  Heading,
  Image,
} from '@chakra-ui/react';
import Navbar from '../components/Navbar';
import { SearchIcon, ArrowForwardIcon } from '@chakra-ui/icons';
import { BsFileText } from 'react-icons/bs';
import Category from '../components/Category';

export default function Home() {
  // this is just testing api connection, possibly could be remove
  const [checkApi, setCheckApi] = useState('');
  const fetchApi = async () => {
    try {
      const result = await axios.get();
      setCheckApi(result);
    } catch (error) {
      console.log(error);
    }
  };
  useEffect(() => {
    fetchApi();
  }, []);
  console.log(checkApi);
  // end of testing api

  return (
    <Box>
      <Head>
        <title>Medbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Start Navbar */}
      <Navbar />
      {/* End Navbar */}

      {/* Start Banner */}
      <Show breakpoint="(max-width: 576px)">
        <Box bgColor={'blue.500'} height={'5vh'}></Box>

        <InputGroup
          w={'50%'}
          mx="auto"
          top={'-2vh'}
          backgroundColor="white"
          rounded={10}
        >
          <Input type="text" placeholder="Cari Obat" />
          <InputRightElement h={'full'}>
            <Button variant={'ghost'}>
              <SearchIcon />
            </Button>
          </InputRightElement>
        </InputGroup>
      </Show>

      {/* End Banner */}

      {/* Start Upload Resep */}
      <Flex bg="#F2F8FC" mx="4" height={'10vh'} marginBottom="4">
        <Icon
          as={BsFileText}
          width="15%"
          height="100%"
          color={'#005E9D'}
          p="2"
        />
        <Box p="2" flex="1">
          <Text fontWeight={'semibold'}>Punya Resep Dokter?</Text>
          <Text fontWeight={'light'}>
            klik disini untuk kirim foto resep dokter
          </Text>
        </Box>
        <ArrowForwardIcon
          p="2"
          width="15%"
          height="100%"
          textColor={'#005E9D'}
        />
      </Flex>
      {/* End Upload Resep */}

      {/* Start Category */}
      <Box mx="4" maxHeight={'20vh'}>
        <Text fontSize="xl" fontWeight={'semibold'}>
          Jelajahi Kategori Obat
        </Text>
        <Category />
      </Box>
      {/* End Category */}
    </Box>
  );
}
